Task 7: file copying
dan0st/tasks_repo pull request #7
Opened 2023-01-10 19:58 UTC by dan0st

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-13 13:54 UTC, vladislavmass requested changes
По большому счету все, что находится внутри copy.go это условная библоиотека и завязывать код библиотеки на конкретную реализацию( в данном случае на работу через консоль) это не правильно.

2023-01-13 13:54 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +func filesValidation(sourceFile string, destinationFile string, forceFlag bool) error {
Правильнее с точки зрения архитектуры кода разбить на 2 метода. Валидация  источника и валидация целевого метода.  Также как вариант тут можно выделить общий код в единый метод, который будет возвращать статус и конкретный метод валидации уже будет принимать решение ошибка это или  нет.

2023-01-13 13:54 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if offset < 0 || limit < 0 {
Лучше эту проверку делать до вызова проверки filesValidation. Всегда лучше легкие проверки делать перед тяжелыми

2023-01-17 00:47 UTC, dan0st commented on hw07_file_copying/copy.go
> +	if offset < 0 || limit < 0 {
Done

2023-01-17 00:48 UTC, dan0st commented on hw07_file_copying/copy.go
> +func filesValidation(sourceFile string, destinationFile string, forceFlag bool) error {
Done

2023-01-17 07:10 UTC, vladislavmass approved these changes
Работу принимаю 10/10

2023-01-17 07:10 UTC, vladislavmass commented on hw07_file_copying/copy_test.go
> +	t.Run("non-existent destination path", func(t *testing.T) {
С такими тестами поосторожнее. Так как этот тест при запуске на винде будет падать.

2023-01-17 11:06 UTC, vladislavmass approved these changes
Работа принята

2023-01-17 12:28 UTC, merged